---
#
# Copyright (c) 2018, Intel Corporation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

# tasks file for trafficserver

  - name: Legal message
    debug:
      msg: "This script will install third party components licensed under various open source licenses onto your system/device/server. The terms under which those components may be used and distributed can be found with the license document that is provided with those components. Please familiarize yourself with those terms to ensure your distribution of those components complies with the terms of those licenses." 

  - name: Include ATS dependencies for RedHat/CentOS
    include: centos_rhel_dep.yml
    when: ansible_distribution in ['RedHat', 'CentOS']

  - name: Include ATS dependencies for Debian
    include: debian_dependencies.yml
    when: ansible_os_family == "Debian"


  - name: Cloning trafficserver from github
    git:
      repo: "{{ ats_git_url }}"
      dest: /opt/trafficserver
      update: yes
      force: yes
      version: "{{ ats_version }}"


  - name: Compiling and installing traffic_server
    become: yes
    shell: "{{ item }}"
    args:
      chdir: "{{ ats_install_dir }}"
    with_items:
      - autoreconf -if
      - ./configure --prefix={{ ats_bin_path }} {{ ats_custom_modules }}
      - make -j$(nproc)
      - make -j$(nproc) install


  - name: Copying optimal record.config configuration file
    template:
     src: "records.config.tpl"
     dest: "{{ ats_record_conf_path }}"
    notify:
    - Restart trafficserver

  - name: Copying optimal remap.config configuration file
    template:
     src: "remap.config.tpl"
     dest: "{{ ats_remap_conf_path }}"
    notify:
    - Restart trafficserver

  - name: Copying optimal storage.config configuration file
    template:
     src: "storage.config.tpl"
     dest: "{{ ats_storage_conf_path }}"
    notify: Restart trafficserver

