---
#
# Copyright 2017 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
# THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

# vars file for trafficserver

    ats_version: "7.1.5"
    ats_git_url: "https://github.com/apache/trafficserver.git"
    ats_install_dir: "/opt/trafficserver"
    ats_bin_path: "/opt/ats"
    ats_record_conf_path: "/opt/ats/etc/trafficserver/records.config"
    ats_remap_conf_path: "/opt/ats/etc/trafficserver/remap.config"
    ats_storage_conf_path: "/opt/ats/etc/trafficserver/storage.config"
    ats_custom_modules: "--enable-experimental-plugins --enable-example-plugins --enable-ccache --enable-werror --enable-debug"
