---
#
# Copyright (c) 2018, Intel Corporation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
#     * Neither the name of the copyright holder nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#


# Tasks file for ffmpeg

  - name: Legal message
    debug:
      msg: "This script will install third party components licensed under various open source licenses onto your system/device/server. The terms under which those components may be used and distributed can be found with the license document that is provided with those components. Please familiarize yourself with those terms to ensure your distribution of those components complies with the terms of those licenses."


  - name: Include FFMpeg dependencies for Debian
    include: debian_dependencies.yml
    when: ansible_os_family == "Debian" 

 
  - name: Include FFMpeg dependencies for RedHat/CentOS
    include: centos_rhel_dep.yml
    when: ansible_distribution in ['RedHat', 'CentOS']


  - name: Cloning ffmpeg from github
    git:
      repo: "{{ ffmpeg_git_url }}"
      dest: "{{ ffmpeg_install_dir }}"
      update: yes
      force: yes
      version: "{{ ffmpeg_version }}"
    register: ffmpeg_source

  
  - name: Configuring and Installing ffmpeg for Debian
    shell: "{{ item }}"
    args:
      chdir: "{{ ffmpeg_install_dir }}"
    with_items:
      - ./configure {{ ffmpeg_custom_modules_debian }}
      - make -j$(nproc)
      - make -j$(nproc) install
    when: ansible_os_family == "Debian"


  - name: Configuring and Installing ffmpeg for RedHat/CentOS
    shell: "{{ item }}"
    args:
      chdir: "{{ ffmpeg_install_dir }}"
      creates: "{{ ffmpeg_bin_dir }}/ffmpeg"
    with_items:
      - PKG_CONFIG_PATH="{{ ffmpeg_build_dir }}/lib/pkgconfig" ./configure {{ ffmpeg_custom_modules_rhel }}
      - make -j$(nproc)
      - make -j$(nproc) install
      - make distclean
      - hash -r
    when: ansible_distribution in ['RedHat', 'CentOS']


