---
#
# Copyright 2017 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom
# the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
# THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# Authour: Pushpendra Kumar (pushpendra.kumar@intel.com)
# Intel Corporation
#


# Tasks file for ffmpeg

  - name: Legal message
    debug:
      msg: "This script will install third party components licensed under various open source licenses onto your system/device/server. The terms under which those components may be used and distributed can be found with the license document that is provided with those components. Please familiarize yourself with those terms to ensure your distribution of those components complies with the terms of those licenses."


  - name: Include FFMpeg dependencies for Debian
    include: debian_dependencies.yml
    when: ansible_os_family == "Debian" 

 
  - name: Include FFMpeg dependencies for RedHat/CentOS
    include: centos_rhel_dep.yml
    when: ansible_distribution in ['RedHat', 'CentOS']


  - name: Cloning ffmpeg from github
    git:
      repo: "{{ ffmpeg_git_url }}"
      dest: "{{ ffmpeg_install_dir }}"
      update: yes
      force: yes
      version: "{{ ffmpeg_version }}"
    register: ffmpeg_source

  
  - name: Configuring and Installing ffmpeg for Debian
    shell: "{{ item }}"
    args:
      chdir: "{{ ffmpeg_install_dir }}"
    with_items:
      - ./configure {{ ffmpeg_custom_modules_debian }}
      - make -j$(nproc)
      - make -j$(nproc) install
    when: ansible_os_family == "Debian"


  - name: Configuring and Installing ffmpeg for RedHat/CentOS
    shell: "{{ item }}"
    args:
      chdir: "{{ ffmpeg_install_dir }}"
      creates: "{{ ffmpeg_bin_dir }}/ffmpeg"
    with_items:
      - PKG_CONFIG_PATH="{{ ffmpeg_build_dir }}/lib/pkgconfig" ./configure {{ ffmpeg_custom_modules_rhel }}
      - make -j$(nproc)
      - make -j$(nproc) install
      - make distclean
      - hash -r
    when: ansible_distribution in ['RedHat', 'CentOS']


